"""Write _preview.html: README rendered the way GitHub's profile page shows it.

    python scripts/preview.py          # then open _preview.html in a browser

- 848px column + github-markdown-css, dark by default; buttons switch the page theme.
- Open with #classic to start on the Classic view (handy for headless screenshots).
- Local images that Actions has not generated yet get a visible placeholder.
_preview.html is git-ignored.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PAGE = """<!doctype html>
<html data-theme="dark"><head><meta charset="utf-8"><title>Tim-1e profile · preview</title>
<link id="css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown-dark.min.css">
<style>
  body {{ margin: 0; background: #0d1117; font-family: system-ui, sans-serif; }}
  html[data-theme=light] body {{ background: #ffffff; }}
  .box {{ max-width: 848px; margin: 24px auto; padding: 24px; border: 1px solid #30363d; border-radius: 6px; }}
  .markdown-body img {{ max-width: 100%; box-sizing: content-box; }}
  .markdown-body summary {{ cursor: pointer; }}
  .bar {{ position: fixed; top: 12px; right: 12px; display: flex; gap: 6px; z-index: 9; }}
  .bar button {{ font: 12px monospace; padding: 6px 10px; border: 1px solid #30363d; background: #161b22; color: #e6edf3; border-radius: 6px; cursor: pointer; }}
  .missing {{ display: inline-block; padding: 18px; border: 1px dashed #d29922; color: #d29922; font: 13px monospace; }}
</style></head>
<body>
<div class="bar"><span style="color:#8b949e;font:12px monospace;align-self:center">PREVIEW</span>
  <button onclick="theme('dark')">dark</button><button onclick="theme('light')">light</button></div>
<article class="markdown-body box">
{body}
</article>
<script>
  function theme(t) {{
    document.documentElement.dataset.theme = t;
    document.getElementById('css').href = 'https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.5.1/github-markdown-' + t + '.min.css';
  }}
  if (location.hash === '#classic') document.querySelectorAll('details[name=view]')[0].open = true;
  if (location.hash === '#light') theme('light');
</script>
</body></html>
"""


def main():
    body = (ROOT / "README.md").read_text(encoding="utf-8")

    def check(match):
        src = match.group(1)
        if src.startswith("./") and not (ROOT / src[2:]).exists():
            return f'<span class="missing">{src[2:]} — generated by Actions after push</span>'
        return match.group(0)

    body = re.sub(r'<img src="(\./[^"]+)"[^>]*>', check, body)
    out = ROOT / "_preview.html"
    out.write_text(PAGE.format(body=body), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
